language: php
sudo: false
php:
  - 7.0
  - 7.1
matrix:
  include:
    - php: 7.0
      env: dependencies=lowest
    - php: 7.0
      env: dependencies=highest
    - php: 7.1
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=highest
before_script:
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - stty cols 80 # weird Travis CI issue with PHPUnit ResultPrinter https://github.com/sebastianbergmann/phpunit/issues/1976
script:
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpcs --standard=ruleset.xml src tests
  - ./vendor/bin/phpstan analyze -l 7 --configuration=tests/phpstan.neon src tests
after_script:
  - php vendor/bin/coveralls -v
